# Generated by Django 4.0.5 on 2022-06-13 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0003_alter_tenant_date_of_birth'),
        ('charge_accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid'), ('late', 'Late')], default='unpaid', max_length=25)),
                ('is_late_charge', models.BooleanField(default=False)),
                ('charge_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('memo', models.CharField(blank=True, max_length=150)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('charge_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charge_accounts.chargeaccount')),
                ('parent_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_charges', to='charges.charge')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='tenants.tenant')),
            ],
        ),
    ]
