# Generated by Django 4.0.5 on 2022-06-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='addr_line_1',
            field=models.CharField(max_length=100, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='addr_line_2',
            field=models.CharField(blank=True, max_length=100, verbose_name='Address Line 2'),
        ),
    ]
