# Generated by Django 4.0.5 on 2022-06-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0004_alter_unit_percentage_of_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
