# Generated by Django 4.0.4 on 2022-06-01 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0003_alter_company_addr_city_alter_company_addr_line_1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_built', models.DateField(blank=True, verbose_name='Date Built')),
                ('key_number', models.IntegerField(blank=True, verbose_name='Key Number')),
                ('description', models.CharField(blank=True, max_length=250)),
                ('addr_line_1', models.CharField(max_length=100, verbose_name='Address Line 1')),
                ('addr_line_2', models.CharField(blank=True, max_length=100, verbose_name='Address Line 2')),
                ('addr_city', models.CharField(max_length=50, verbose_name='City')),
                ('addr_state', models.CharField(max_length=25, verbose_name='State')),
                ('addr_zip', models.CharField(max_length=20, verbose_name='Zip Code')),
                ('property_type', models.CharField(choices=[('commercial', 'Commercial'), ('residential', 'Residential'), ('billboard', 'Billboard'), ('tower', 'Tower')], default='commercial', max_length=20, verbose_name='Property Type')),
                ('square_feet', models.IntegerField(default=0)),
                ('taxes', models.IntegerField(default=0)),
                ('insurance', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='companies.company')),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
    ]
