# Generated by Django 4.0.4 on 2022-06-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='date_built',
            field=models.DateField(blank=True, null=True, verbose_name='Date Built'),
        ),
    ]
