# Generated by Django 4.0.4 on 2022-06-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_property_date_built'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='key_number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Key Number'),
        ),
    ]
