# Generated by Django 4.0.4 on 2022-06-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_key_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='insurance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
