# Generated by Django 4.0.4 on 2022-06-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_alter_property_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='taxes',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
