# Generated by Django 4.0.5 on 2022-06-10 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='deleted_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
