# Generated by Django 4.0.4 on 2022-05-31 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('addr_line_1', models.CharField(max_length=50)),
                ('addr_line_2', models.CharField(max_length=50)),
                ('addr_city', models.CharField(max_length=50)),
                ('addr_state', models.CharField(max_length=25)),
                ('addr_zip', models.CharField(max_length=15)),
                ('phone', models.CharField(max_length=20)),
                ('alt_phone', models.CharField(max_length=20)),
                ('fax', models.CharField(max_length=20)),
                ('is_deleted', models.BooleanField()),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
    ]
